### ISSUE TITLE
Issue with unescaped characters

### ISSUE THREAD

**Issue by chipoglesby** [fkeck/subtools#1]
Hi @fkeck, great work on the package, I love it.

I have noticed an issue when using `read.subtitles.serie`. 

For some reason, the program seems to stop when it finds an unescaped question mark in the middle of sentence.

For example with:

```
146
00:06:42,262 --> 00:06:48,947
Say... any chance of, er, getting a table for four on Saturday at, et, say... eight, hmm?

147
00:06:49,563 --> 00:06:51,047
Merci, a bient?t!

148
00:06:51,048 --> 00:06:52,366
Ah! We're in!

149
00:06:53,704 --> 00:06:55,039
Niles, can I get you a beer?
```

The import stops after `Merci, a bient?t!`. I have [my code and data here](https://github.com/chipoglesby/frasier) if you would like to take a look.

Do you think it's something that could be stopped if I did some preprocessing on the `srt` files before importing?

**Comment by chipoglesby** [comment]
Upon closer inspection, I think it may have to do with the way the files are encoded.

For example, 

```
74
00:04:48,142 --> 00:04:51,221
You�re right about that woman at the 
computer though, she's a looker.
```
Converting the files to utf-8 seemed to fix the error.

**Comment by fkeck** [comment]
Yes. You can set the encoding with the encoding argument of read.subtitles. Default is UTF8.
