### ISSUE TITLE
Would you mind supporting *.vtt file for read.subtitles() function?

### ISSUE THREAD

**Issue by jooyoungseo** [fkeck/subtools#4]
Hello,

I was wondering if you mind supporting *.vtt file format for `read.subtitles()` format as `youtube-dl` python library downloads YouTube captions as *.vtt by default.
Of course, I could try to convert a vtt into an srt; however, it would be much more convenient if I could import vtt files through the `read.subtitles()` function as well.
Many thanks.

**Comment by fkeck** [comment]
Hi,
This is an interesting feature I would like to add in the future. However, I have currently no time to work on that, so in the meantime I think you will have to do a conversion.

**Comment by fkeck** [comment]
Hi,
subtools now has basic support for WebVTT format (.vtt).
Please open a new issue if you encounter any problem with this functionality.

**Comment by jooyoungseo** [comment]
Thank you very much for your kind consideration and hard work!
Would you mind testing the attached vtt file `test.vtt.txt` (I had to changed the file extension for upload; however, please changed it back into .vtt when you test!).

I see repeated redundancies in text column (please take a look at the results below):

``` r
test <- subtools::read.subtitles('test.vtt')

head(test[[1]])
##   ID  Timecode.in Timecode.out
## 1  1 00:00:00.060 00:00:02.330
## 2  2 00:00:02.330 00:00:02.340
## 3  3 00:00:02.340 00:00:05.329
## 4  4 00:00:05.329 00:00:05.339
## 5  5 00:00:05.339 00:00:07.280
## 6  6 00:00:07.280 00:00:07.290
##                                                                             Text
## 1                                              so today I wanted to talk about a
## 2                                            so today I wanted to talk about a  
## 3     so today I wanted to talk about a lobster which is a new package that I've
## 4                                     lobster which is a new package that I've  
## 5 lobster which is a new package that I've been working on as part of the second
## 6                                        been working on as part of the second

tail(test[[1]])
##        ID  Timecode.in Timecode.out
## 1732 1732 00:38:04.920 00:38:04.930
## 1733 1733 00:38:04.930 00:38:07.520
## 1734 1734 00:38:07.520 00:38:07.530
## 1735 1735 00:38:07.530 00:38:27.120
## 1736 1736 00:38:27.120 00:38:27.130
## 1737 1737 00:38:27.130 00:38:29.190
##                                                        Text
## 1732                up you talk to some other specialized  
## 1733 up you talk to some other specialized system thank you
## 1734                                     system thank you  
## 1735                            system thank you [Applause]
## 1736                                                       
## 1737                                                    yo
```

[test.vtt.txt](https://github.com/fkeck/subtools/files/2587010/test.vtt.txt)

**Comment by fkeck** [comment]
Hi,
I just checked and the redundancies seems to come from your file, not from the function `read.subtitles`
