### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by psimm** [fkeck/subtools#7]
Hi @fkeck!

thank you for building subtools. It has been tremendously helpful when working with subtitles from YouTube videos.

Would you please consider adding a license? This would make it easier to use your package at companies. Perhaps the  
[MIT license](https://www.r-project.org/Licenses/MIT) is a good fit for your project. Here is a guide to licensing R packages: <https://r-pkgs.org/license.html>.

Best regards
Paul

**Comment by fkeck** [comment]
Hi Paul,
Thanks for your message, the subtools package is distributed under the terms of the the GPL-3 licence. This is indicated in the DESCRIPTION file. I hope this is compatible with your intended use.
Best regards,
François

**Comment by psimm** [comment]
Hi François,

Sorry, I didn't check the DESCRIPTION file. Thanks for the quick answer. Yes, the GPL-3 licence works for my usecase.

Best regards,
Paul
